name: CI/CD Workflow

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:


    services:
      mysql:
        image: mysql:8.0.3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: io
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u io --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'xxx'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          scp target/THEproject.war ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/opt/tomcat/webapps/
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} -p ${{ secrets.VPS_PORT }} "sudo systemctl restart tomcat"
